[build]
  # Directorio donde están los archivos fuente
  base = "."
  
  # Comando para construir el proyecto
  command = "npm run build"
  
  # Directorio donde se generan los archivos estáticos
  publish = "build"

[build.environment]
  # Variables de entorno para el build
  NODE_VERSION = "18"

# Redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    # Seguridad básica
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS para Supabase
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Configuración para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"